project/users/views.py
# -*- coding: utf-8 -*-

from flask import flash, redirect, render_template, request, session, url_for, Blueprint
from forms import RegisterForm, LoginForm
from sqlalchemy.exc import IntegrityError
from project.views import login_required
from project.models import User
from project import db, bcrypt


users_blueprint = Blueprint(
    'users', __name__,
    url_prefix ='/users',
    template_folder='templates',
    static_folder='static'
)



@users_blueprint.route('/logout/')
@login_required
def logout():
    session.pop('logged_in', None)
    session.pop('user_id', None)
    session.pop('role', None)
    session.pop('name', None)
    flash("You have been logged out!")
    return redirect(url_for('users.login'))


@users_blueprint.route('/', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            u = User.query.filter_by(name=request.form['name']).first()
            if u is None:
                error = 'Invalid credentials'
                return render_template('login.html', form=form, error=error)
            elif bcrypt.check_password_hash(u.password, request.form['password']):
                session['logged_in'] = True
                session['user_id'] = u.id
                session['role'] = u.role
                session['name'] = u.name
                flash("Legged in successfully")
                return redirect(url_for('tasks.tasks'))
        else:
            error = 'not valid data in form'
            return render_template('login.html', form=form, error=error)
    if request.method == 'GET':
        return render_template('login.html', form=form, error=error)

@users_blueprint.route('/register/', methods=['GET', 'POST'])
def register():
    error = None
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_user = User(form.name.data,
                            form.email.data,
                            bcrypt.generate_password_hash(form.password.data))
                            # form.password.data)
            try:
                db.session.add(new_user)
                db.session.commit()
                flash('Thanks for registering')
                return redirect(url_for('users.login'))
            except IntegrityError:
                error = 'already taken'
                return render_template('register.html', form=form, error=error)
        else:
            error = 'Not valid data in form!'
            return render_template('register.html', form=form, error=error)
    if request.method == 'GET':
        return render_template('register.html', form=form)

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (getattr(form, field).label.text, error), 'error')

project/templates/template.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>welcome to flasktaskr</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <script src="{{ url_for('static', filename='js/jquery-1.11.2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>

        </button>
        <a class="navbar-brand" href="/">FlaskTaskr</a>

    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            {% if not session.logged_in %}
            <li><a href="{{ url_for('users.register') }}">Singup</a> </li>
            {% else %}
            <li><a href="{{ url_for('users.logout') }}">Logout</a> </li>
            {% endif %}
        </ul>
        {% if session.logged_in %}
        <ul class="nav navbar-nav navbar-right">
            <li><a>Welcome, {{ username }}</a> </li>
        </ul>
        {% endif %}
    </div>
</div>

<div class="container">
    <div class="content">
    {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
    {% endfor %}
    {% if error %}
        <div class="error"><strong>Error:</strong>{{ error }}</div>
    {% endif %}

    {% block content %}
    {% endblock %}
    </div>
    <div class="footer">
        <hr>
        <p>&copy; <a href="http://www.realpython.com">RealPython</a></p>

    </div>
</div>

</div>
</body>
</html>