project/tasks/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import TextField, DateField, IntegerField, \
    SelectField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo, Email


class AddTaskForm(Form):
    task_id = IntegerField('Priority')
    name = TextField('Task Name', validators=[DataRequired()])
    due_date = DateField('Date Due (mm/dd/yyyy)', validators=[DataRequired()], format='%m/%d/%Y')
    priority = SelectField('Priority', validators=[DataRequired()],
                           choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5',
                                                                                     '5'),
                                    ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10',
                                                                                     '10')])
    status = IntegerField('Status')

project/tasks/__init__.py
# -*- coding: utf-8 -*-

project/tasks/views.py
# -*- coding: utf-8 -*-
import datetime

from flask import flash, redirect, render_template, request, session, url_for, Blueprint
from project.views import login_required
from forms import AddTaskForm
from project.models import Task
from project import db

tasks_blueprint = Blueprint(
    'tasks', __name__,
    url_prefix='/tasks',
    template_folder='templates',
    static_folder='static'
)



@tasks_blueprint.route('/tasks/')
@login_required
def tasks():
    open_tasks = db.session.query(Task).filter_by(status='1').order_by(Task.due_date.asc())
    closed_tasks = db.session.query(Task).filter_by(status='0').order_by(Task.due_date.asc())
    return render_template('tasks.html', form=AddTaskForm(request.form), open_tasks=open_tasks,
                           closed_tasks=closed_tasks, username=session['name'])


@tasks_blueprint.route('/add/', methods=['POST'])
@login_required
def new_task():
    form = AddTaskForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_task = Task(form.name.data, form.due_date.data, form.priority.data, '1', session['user_id'],
                            datetime.datetime.now())
            db.session.add(new_task)
            db.session.commit()
            flash("New entry added succesfully")
            return redirect(url_for('tasks.tasks'))
        else:
            error = 'Not valid data in form!'
            return render_template('tasks.html', error=error, form=form)


@tasks_blueprint.route('/complete/<int:task_id>/',)
@login_required
def complete(task_id):
    new_id = task_id
    task = db.session.query(Task).filter_by(task_id=new_id)
    if session['user_id'] == task.first().user_id or session['role'] == "admin":
        task.update({"status": "0"})
        db.session.commit()
        flash("Task marked as complete")
        return redirect(url_for('tasks.tasks'))
    else:
        flash("Not permitted")
        return redirect(url_for('tasks.tasks'))


@tasks_blueprint.route('/delete/<int:task_id>/')
@login_required
def delete_entry(task_id):
    new_id = task_id
    task = db.session.query(Task).filter_by(task_id=new_id)
    if session['user_id'] == task.first().user_id or session['role'] == "admin":
        task.delete()
        db.session.commit()
        flash("Task deleted")
        return redirect(url_for('tasks.tasks'))
    else:
        flash("Not permitted")
        return redirect(url_for('tasks.tasks'))

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (getattr(form, field).label.text, error), 'error')

project/tasks/templates/tasks.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% extends 'template.html' %}
{% block content %}
    <h1>welcome in flastaskr</h1>
    <a href=" {{ url_for('users.logout') }}">Logout</a>

    <div class="add-task">
        <div class="lead">Add a new task:</div>
        <form action="{{ url_for('tasks.new_task') }}" method="post">
            {{ form.csrf_token }}
            <p>
                {{ form.name(placeholder="name") }}
            <span class="error">
            {% if form.name.errors %}
                {% for error in form.name.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
            </span>
            </p>

            <p>
                {{ form.due_date(placeholder="due date") }}
            <span class="error">
            {% if form.due_date.errors %}
                {% for error in form.due_date.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
            </span>
            </p>

            <p>
                {{ form.priority.label }}
                {{ form.priority(class="form-control",style="max-width:60px;") }}
                <span class="error">
                {% if form.priority.errors %}
                    {% for error in form.priority.errors %}
                        {{ error }}
                    {% endfor %}
                {% endif %}
                </span>
            </p>
        <p><button class="btn btn-sm btn-success" type="submit">Submit</button></p>
        </form>
    </div>
    <div class="entries">
        <br>
        <br>

        <div class="lead">Open tasks</div>

        <div class="datagrid">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><strong>Task Name</strong></th>
                    <th><strong>Due Date</strong></th>
                    <th><strong>Posted Date</strong></th>
                    <th><strong>Priority</strong></th>
                    <th><strong>Posted by</strong></th>
                    <th><strong>Actions</strong></th>
                </tr>
                </thead>
                {% for o in open_tasks %}
                    <tr>
                        <td>{{ o.name }}</td>
                        <td>{{ o.due_date }}</td>
                        <td>{{ o.posted_date }}</td>
                        <td>{{ o.priority }}</td>
                        <td>{{ o.poster.name }}</td>
                        {% if o.poster.name == session.name or session.role == "admin" %}
                        <td>
                            <a href="{{ url_for('tasks.delete_entry', task_id = o.task_id) }}">Delete</a>
                            <a href="{{ url_for('tasks.complete', task_id = o.task_id) }}">MArk as Complete</a>
                        </td>
                        {% else %}
                        <span>N/A</span>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>
        <br>
        <br>
    </div>
    <div class="entries">
        <div class="lead">Closed tasks</div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th><strong>Task Name</strong></th>
                <th><strong>Due Date</strong></th>
                <th><strong>Posted Date</strong></th>
                <th><strong>Priority</strong></th>
                <th><strong>Posted by</strong></th>
                <th><strong>Actions</strong></th>
            </tr>
            </thead>
            {% for o in closed_tasks %}
                <tr>
                    <td>{{ o.name }}</td>
                    <td>{{ o.due_date }}</td>
                    <td>{{ o.posted_date }}</td>
                    <td>{{ o.priority }}</td>
                    <td>{{ o.poster.name }}</td>

                    {% if o.poster.name == session.name or session.role == "admin" %}
                    <td>
                        <a href="{{ url_for('tasks.delete_entry', task_id = o.task_id) }}">Delete</a>
                    </td>
                    {% else %}
                        <span>N/A</span>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
    <br>
    <br>
    </div>
{% endblock %}
</body>
</html>